---
title: "R Notebook"
output: html_notebook
---


```{r}
# Load packages
library(tidyverse)
library(httr)
library(jsonlite)
```


# source the config file with the Slack API token and channel ID
```{r}
source(".config")
```

##
```{r}
url_slack <- 'https://slack.com/api/groups.history'

url <- str_c(url_slack, "?", "token=", token, "&", "channel=", channel, "&pretty=1")
url
```



```{r}
a <- GET(url)
a
```

```{r}
msgs <- content(a)$messages


```


```{r}
nest2df <- function(x){
  tribble(
    ~user, ~text, ~timestamp, ~reaction,
    x$user,  x$text, x$ts, x$reaction
  )
}


```


```{r}
library(purrr)
msgs_df <- map_df(msgs, nest2df)
msgs_df
```



```{r}
#query api for actual name's
getUserRealName <- function(userid, api_token=token){
  # construct the API URL
  userInfoURL <- str_c('https://slack.com/api/users.info?token=', api_token, '&user=', userid, '&pretty=1') 
  
  # pull the user's real name from the API response
  real_name <- content(GET(userInfoURL))$user$real_name
  return(real_name)
}

getUserRealName(ids[1])


```

```{r}
msgs_df %>% rowwise() %>% mutate(name=getUserRealName(user))
```

```{r}
test_df <- bind_rows(replicate(1000, msgs_df, simplify = FALSE))

#test_df %>% rowwise() %>% mutate(name=getUserRealName(user))
test_df
```

```{r}
# get unique user names from ID's
realNames <- test_df %>% select(user) %>% unique() %>% rowwise() %>% mutate(real_name=getUserRealName(user))
msgs_df_names <- left_join(test_df, realNames, by='user')
```
